# Exercise: Data Summarization (Key)

In [1]:
import pandas as pd
import numpy as np

In [2]:
from nycflights13 import flights
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

## DataFrame with columns

- year,month,day
        Date of departure    
- dep_time,arr_time
        Actual departure and arrival times (format HHMM or HMM), local tz.
- sched_dep_time,sched_arr_time
        Scheduled departure and arrival times (format HHMM or HMM), local tz.    
- dep_delay,arr_delay
        Departure and arrival delays, in minutes. Negative times represent early departures/arrivals.
- hour,minute
        Time of scheduled departure broken into hour and minutes.
- carrier
        Two-letter carrier abbreviation. See airlines() to get name
- tailnum
        Plane tail number
- flight
        Flight number
- origin,dest
        Origin and destination. See airports() for additional metadata.
- air_time
        Amount of time spent in the air, in minutes
- distance
        Distance between airports, in miles
- time_hour
        Scheduled date and hour of the flight as a date. Along with origin, can be used to join flights data to weather data.

In [3]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   year            336776 non-null  int64
 1   month           336776 non-null  int64
 2   day             336776 non-null  int64
 3   dep_time        328521 non-null  float64
 4   sched_dep_time  336776 non-null  int64
 5   dep_delay       328521 non-null  float64
 6   arr_time        328063 non-null  float64
 7   sched_arr_time  336776 non-null  int64
 8   arr_delay       327346 non-null  float64
 9   carrier         336776 non-null  object
 10  flight          336776 non-null  int64
 11  tailnum         334264 non-null  object
 12  origin          336776 non-null  object
 13  dest            336776 non-null  object
 14  air_time        327346 non-null  float64
 15  distance        336776 non-null  int64
 16  hour            336776 non-null  int64
 17  minute          336776 non-null  int64
 18  time_hour       336776 non-null  object
dtypes: float64(5), int64(9), object(5)
memory usage: 48.8+ MB

## Exercises

Write Python scripts to answer the following questions.

In [4]:
# How many distinct airplanes are there in this dataset? 
flights.tailnum.nunique()

4043

In [5]:
# Which hours of the day are the busiest? 
# List the top 5 hours with the most flights. 
flights.hour.value_counts().head()

hour
8     27242
6     25951
17    24426
15    23888
16    23002
Name: count, dtype: int64

In [6]:
(
    flights
    .groupby('hour')
    .agg({'flight':'count'})
    .sort_values('flight',ascending=False)
    .head()
)

      flight
hour
8      27242
6      25951
17     24426
15     23888
16     23002

In [7]:
# Find all flights (identified by 'carrier' and 'flight') 
# that always depart at least 60 minutes late.

(flights.groupby(['carrier','flight'])
 .agg({'dep_delay':'min'})
 .query('dep_delay>=60'))

                dep_delay
carrier flight
9E      3283        104.0
        3297        120.0
        3546         64.0
        3583         95.0
        3588        115.0
        3682         66.0
        3760        217.0
B6      205          82.0
DL      390         334.0
        462         125.0
        809         298.0
        917         157.0
        2390         92.0
EV      4151         67.0
        4320         95.0
        4564         91.0
        4617        128.0
        5015         63.0
        5062        111.0
        5071         92.0
        5083         98.0
        5117        219.0
        5294        192.0
        5358         78.0
        5409         87.0
        5425         62.0
        5478        242.0
        5629         71.0
        5668        106.0
        5839         65.0
        5855        209.0
        6082        153.0
        6093        128.0
F9      2001         65.0
OO      8500         67.0
UA      18           95.0
        125          89.0
        348          93.0
        546          60.0
        640         115.0
        945          62.0
        993          69.0
        1510        278.0
US      1226        147.0
WN      217         195.0
        521         346.0
        718          78.0
        1019        203.0
        2521         79.0
        2529         75.0
        3032         90.0
        3791        151.0
YV      3799        168.0

In [8]:
# How many flights always depart at least 60 minutes late?
late_flights = (flights.groupby(['carrier','flight'])
 .agg({'dep_delay':'min'})
 .query('dep_delay>=60'))
late_flights.shape[0]

53

In [9]:
# Find all United Airlines (UA) flights (identified by 'carrier' and 'flight') 
# that depart (at least) 60 minutes late.

(flights[flights.carrier=='UA'].groupby(['carrier','flight'])
 .agg({'dep_delay': 'min'})
 .query('dep_delay>=60')
)

                dep_delay
carrier flight
UA      18           95.0
        125          89.0
        348          93.0
        546          60.0
        640         115.0
        945          62.0
        993          69.0
        1510        278.0

In [10]:
# How many United Airlines (UA) flights depart (at least) 60 minutes late?
(flights[flights.carrier=='UA'].groupby(['carrier','flight'])
 .agg({'dep_delay': 'min'})
 .query('dep_delay>=60')
).shape[0]

8

In [ ]:
# Which flights always arrived on time in December? 
(flights[flights.month==12]
 .groupby(['carrier','flight'])
 .agg({'arr_delay': 'max'})
 .query('arr_delay<=0')
)

                arr_delay
carrier flight
9E      2909         -7.0
        2919        -32.0
        2934        -22.0
        2939        -21.0
        2950          0.0
...                   ...
WN      4313        -18.0
        4337        -22.0
        4490         -2.0
        4514         -2.0
        4976        -17.0

[330 rows x 1 columns]

In [12]:
# How many flights always arrived on time in December? 
(flights[flights.month==12]
 .groupby(['carrier','flight'])
 .agg({'arr_delay': 'max'})
 .query('arr_delay<=0')
).count()

arr_delay    330
dtype: int64

In [13]:
# Create a dataframe 'cancelled' for all cancelled flights. 
# Assumption: flights that are not cancelled should have values for dep_time. 

cancelled = flights[flights.dep_time.isnull()] 
cancelled.shape

(8255, 19)

In [14]:
# Look at the number of cancelled flights per day. 
# Find the top 10 days with the most cancelled flights. 

(
    cancelled
    .groupby(['month','day'])
    .agg({'flight':'count'})
    .reset_index()
    .sort_values('flight',ascending=False)
    .head(10)
)

     month  day  flight
38       2    8     472
39       2    9     393
140      5   23     221
336     12   10     204
251      9   12     192
64       3    6     180
66       3    8     180
331     12    5     158
340     12   14     125
199      7   22     123

In [15]:
# Which carrier has the worst average arrival delay? 

(
    flights
    .groupby(['carrier'])
    .agg({'dep_delay':'max'})
    .sort_values('dep_delay', ascending=False)
    .head(10)
)

         dep_delay
carrier
HA          1301.0
MQ          1137.0
AA          1014.0
DL           960.0
F9           853.0
9E           747.0
VX           653.0
FL           602.0
EV           548.0
B6           502.0

In [16]:
# Which plane (tailnum) has the worst on-time record?
(
    flights
    .groupby('tailnum')
    ['dep_delay']
    .agg(['min','max','mean'])
    .sort_values('mean',ascending=False)
    .head(10)
)

           min     max   mean
tailnum
N844MH   297.0   297.0  297.0
N922EV   274.0   274.0  274.0
N587NW   272.0   272.0  272.0
N911DA   268.0   268.0  268.0
N851NW   233.0   233.0  233.0
N654UA   227.0   227.0  227.0
N928DN   203.0   203.0  203.0
N7715E   186.0   186.0  186.0
N665MQ    -8.0  1005.0  177.0
N136DL   165.0   165.0  165.0

In [17]:
# What time (hour) of day should you fly if you want to avoid delays as much as possible?
(
    flights.groupby('hour')
    ['dep_delay']
    .agg(['min','max','mean'])
    .sort_values('mean',ascending=False)
    .head(10)
)

       min     max       mean
hour
19   -30.0  1137.0  24.784791
20   -33.0   878.0  24.304105
21   -43.0   800.0  24.195743
18   -22.0  1014.0  21.110082
17   -27.0   896.0  21.100606
22   -22.0   276.0  18.791097
16   -24.0  1126.0  18.757017
15   -22.0   483.0  16.894565
23   -18.0   245.0  14.017176
14   -32.0   602.0  13.818874

In [18]:
# For each destination, compute the total minutes of arrival delay. 
(
    flights
    .groupby('dest')
    ['arr_delay']
    .agg(['sum'])
    .sort_values('sum',ascending=False)
)

           sum
dest
ATL   190260.0
CLT   100645.0
ORD    97352.0
FLL    96153.0
DCA    82609.0
...        ...
PSP     -229.0
HNL     -957.0
STT    -1987.0
SEA    -4270.0
SNA    -6389.0

[105 rows x 1 columns]

In [ ]:
# Find days whose average arrival delay is greater than 1 hour.
flights.groupby(['year','month','day']).agg({'arr_delay':'mean'}).query('arr_delay>60')

                arr_delay
year month day
2013 3     8    85.862155
     5     23   61.970899
     6     13   63.753689
     7     22   62.763403

In [20]:
# Find the number of carriers between each pair of origin and destination. 

df1 = flights.groupby(['origin','dest','carrier']).agg({'flight':'count'}).reset_index()
df1.groupby(['origin','dest']).agg({'carrier':'count'})

             carrier
origin dest
EWR    ALB         1
       ANC         1
       ATL         4
       AUS         2
       AVL         1
...              ...
LGA    SYR         2
       TPA         2
       TVC         2
       TYS         1
       XNA         2

[224 rows x 1 columns]

In [21]:
# Another solution: 

(
    flights
    .groupby(['origin','dest'])
    .carrier
    .nunique()
)

origin  dest
EWR     ALB     1
        ANC     1
        ATL     4
        AUS     2
        AVL     1
               ..
LGA     SYR     2
        TPA     2
        TVC     2
        TYS     1
        XNA     2
Name: carrier, Length: 224, dtype: int64